"use client";
import "./(protected)/deliveries/delivery.css";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useMutation,useQuery} from "@tanstack/react-query";
import {AlertTriangle,ArrowRight,CheckCircle2,Clock3,CloudRain,Info,PackagePlus,Send,ShieldAlert,Sparkles,Truck,Workflow,X} from "lucide-react";
import {Sidebar} from "@/components/layout/sidebar";import {Topbar} from "@/components/layout/topbar";import {LogisticsMap} from "@/components/map/map";import {Score} from "@/components/route/score";import {RouteCard} from "@/components/route/route-card";import {CreateDeliveryDialog} from "@/components/delivery/create-delivery-dialog";import {DataSourcesPanel} from "@/components/route/data-sources-panel";import {DirectionsPanel} from "@/components/route/directions-panel";import {useOptionalUser} from "@/features/auth/optional-user";import {analyzeRoute} from "@/lib/api";import {platformApi} from "@/lib/platform-api";import {DEMO} from "@/lib/mock-analysis";import {HAZARD_STATUS_TEXT,label} from "@/lib/format";import type {Analysis,AssistantReply} from "@/lib/types";import {useAppStore} from "@/store/app";

const CARGO=[["medicine","Medicine"],["emergency_supplies","Emergency supplies"],["food","Food"],["general_goods","General goods"],["fragile_goods","Fragile goods"],["heavy_cargo","Heavy cargo"]] as const;
const VEHICLES=[["auto","Auto-select"],["cargo_van","Cargo van"],["emergency_cargo_van","Emergency cargo van"],["4x4_utility","4x4 utility"],["pickup_truck","Pickup truck"],["light_truck","Light truck"]] as const;
type ChatMsg={role:"user"|"bot";text:string;source?:string;status?:string};
/** Debounced place suggestions from the backend geocoder (Nominatim needs whole words; results appear after a full token). */
function useSuggestions(query:string){const[debounced,setDebounced]=useState(query);useEffect(()=>{const t=window.setTimeout(()=>setDebounced(query.trim()),600);return()=>window.clearTimeout(t)},[query]);return useQuery({queryKey:["suggest",debounced],queryFn:()=>platformApi.suggest(debounced),enabled:debounced.length>=3,staleTime:600000,retry:0})}

export default function Home(){
  const [analysis,setAnalysis]=useState<Analysis|null>(null);const[origin,setOrigin]=useState<"saved"|"fresh"|"offline-demo"|null>(null);
  const [source,setSource]=useState("Guwahati");const [destination,setDestination]=useState("Shillong");const[cargo,setCargo]=useState<string>("medicine");const[vehicle,setVehicle]=useState<string>("auto");const[departure,setDeparture]=useState<string>(new Date().toISOString());const[dialog,setDialog]=useState(false);
  const[chatOpen,setChatOpen]=useState(false);const[chat,setChat]=useState<ChatMsg[]>([]);const[question,setQuestion]=useState("");const chatEnd=useRef<HTMLDivElement>(null);
  const {selectedRoute,emergency,toggleEmergency,setRoute}=useAppStore();const {user,checked}=useOptionalUser();
  const health=useQuery({queryKey:["health"],queryFn:platformApi.health,staleTime:60000,retry:0});
  const sourceSuggest=useSuggestions(source);const destSuggest=useSuggestions(destination);
  const gemini=health.data?.services?.gemini;
  const mutation=useMutation({mutationFn:analyzeRoute,onSuccess:(result)=>{setAnalysis(result);setOrigin("fresh");setRoute(result.recommended_route_id);setChat([])}});
  // Initial content: the operator's latest saved analysis, otherwise a fresh backend analysis; the bundled demo only when the API is unreachable.
  useEffect(()=>{if(!checked||analysis)return;(async()=>{try{if(user){const h=await platformApi.history(1,1);if(h.items.length){const a=await platformApi.analysis(h.items[0].analysis_id);setAnalysis(a);setOrigin("saved");setRoute(a.recommended_route_id);return}}const fresh=await analyzeRoute({source:{name:source},destination:{name:destination},cargo_type:cargo,vehicle_type:vehicle,priority:"high",emergency_mode:false,departure_time:new Date().toISOString()});setAnalysis(fresh);setOrigin("fresh");setRoute(fresh.recommended_route_id)}catch{setAnalysis(DEMO);setOrigin("offline-demo");setRoute(DEMO.recommended_route_id)}})()},[checked,user,analysis,source,destination,cargo,vehicle,setRoute]);
  useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:"smooth"})},[chat]);
  const ask=useMutation({mutationFn:(q:string)=>platformApi.assistant(q,{analysis_id:analysis?.analysis_id,selected_route_id:selectedRoute,mode:analysis?.mode,routes:analysis?.routes,data_quality:analysis?.data_quality,data_sources:analysis?.data_sources,explanation:analysis?.explanation}),onSuccess:(r:AssistantReply)=>setChat(c=>[...c,{role:"bot",text:r.message,source:r.source,status:r.status}])});
  const send=(q:string)=>{if(!q.trim()||!analysis)return;setChat(c=>[...c,{role:"user",text:q}]);setQuestion("");ask.mutate(q)};

  if(!analysis)return <div className="app"><Sidebar/><main><Topbar/><div className="statePage">{checked?"Running route analysis…":"Loading workspace…"}</div></main></div>;
  const selected=analysis.routes.find(r=>r.id===selectedRoute)||analysis.routes[0];const recommended=analysis.routes.find(r=>r.recommended)||selected;
  const priority=emergency?"critical":"high";
  const canCreate=!!user&&analysis.persistence_status==="persisted"&&!!recommended&&origin!=="offline-demo";
  const submit=(e:React.FormEvent)=>{e.preventDefault();const when=new Date().toISOString();setDeparture(when);mutation.mutate({source:{name:source},destination:{name:destination},cargo_type:cargo,vehicle_type:vehicle,priority,emergency_mode:emergency,departure_time:when})};
  const hazard=selected.hazards;const va=selected.vehicle_assessment;const factorCount=Object.keys(selected.accessibility.factors||{}).length;
  const modeText=origin==="offline-demo"?"Offline demo · API unreachable":analysis.mode==="live"?"LIVE DATA MODE · per-source badges apply":"Demo mode · simulated providers";
  return <div className="app"><Sidebar/><main><Topbar destination={analysis.destination}/><div className="workspace">
    <section className="planner"><div className="sectionTitle"><div><span className="eyebrow">NEW ANALYSIS</span><h2>Plan a reliable route</h2></div><button className={`toggle ${emergency?"on":""}`} onClick={toggleEmergency}><span/><b>Emergency mode</b></button></div>
      <form onSubmit={submit}><label>Source<input value={source} list="source-suggestions" autoComplete="off" onChange={e=>setSource(e.target.value)}/><datalist id="source-suggestions">{sourceSuggest.data?.items.map(i=><option key={i.name} value={i.name}>{i.short}{i.state?` · ${i.state}`:""}</option>)}</datalist></label><div className="connector"/><label>Destination<input value={destination} list="destination-suggestions" autoComplete="off" onChange={e=>setDestination(e.target.value)}/><datalist id="destination-suggestions">{destSuggest.data?.items.map(i=><option key={i.name} value={i.name}>{i.short}{i.state?` · ${i.state}`:""}</option>)}</datalist></label><div className="formRow"><label>Cargo type<select value={cargo} onChange={e=>setCargo(e.target.value)}>{CARGO.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Vehicle<select value={vehicle} onChange={e=>setVehicle(e.target.value)}>{VEHICLES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><button className="analyze" disabled={mutation.isPending}>{mutation.isPending?<><Workflow className="spin" size={18}/>Evaluating corridor…</>:<>Analyze accessibility<ArrowRight size={18}/></>}</button>{mutation.isError&&<div className="formAlert" role="alert" style={{marginTop:10}}><AlertTriangle size={15}/><span><strong>Analysis did not run.</strong> {mutation.error instanceof Error?mutation.error.message:"Analysis failed"}{analysis.mode==="live"?" Place names are resolved with OpenStreetMap; use a town or district name such as “Tezpur, Assam”.":""}</span></div>}{mutation.isSuccess&&<p className="routeOptionsHint">Analysis complete · {analysis.routes.length} route(s) evaluated{analysis.persistence_status==="persisted"?" · saved":""}</p>}</form>
      <div className="routeList"><div className="listLabel"><span>ROUTE OPTIONS</span><small>{origin==="saved"?"Latest saved analysis":origin==="fresh"?"Ranked by reliability":"Bundled demo"}</small></div>{analysis.routes.map(route=><RouteCard key={route.id} route={route}/>)}{analysis.routes.length===1&&<p className="routeOptionsHint">The routing provider returned a single viable route for this corridor; alternatives appear when OSRM offers them.</p>}</div>
    </section>
    <section className="mapPanel"><div className="mapHeader"><div><strong>{analysis.source.name.split(",")[0]}</strong><ArrowRight size={15}/><strong>{analysis.destination.name.split(",")[0]}</strong></div><span><i/> {modeText}</span></div><LogisticsMap analysis={analysis}/><div className="mapNotice"><Info size={15}/>{analysis.data_disclaimer}</div><DirectionsPanel route={selected}/></section>
    <aside className="intelligence"><div className="panelTop"><span className="eyebrow">ROUTE INTELLIGENCE</span><span className="live"><i/>{analysis.persistence_status==="persisted"?"SAVED":origin==="offline-demo"?"OFFLINE DEMO":"NOT SAVED"}</span></div><Score score={selected.accessibility.score} status={selected.accessibility.status}/>
      <div className="keyMetrics"><div><Clock3/><span>Adjusted ETA<strong>{Math.floor(selected.eta_minutes/60)}h {selected.eta_minutes%60}m</strong></span></div><div><Truck/><span>Recommended vehicle<strong>{selected.recommended_vehicle}</strong></span></div></div>
      {va&&<div className="vehicleAssess">{va.requested&&<span>Requested <strong>{va.requested}</strong>: suitability {va.requested_suitability}/100 · recommended <strong>{va.recommended}</strong> {va.recommended_suitability}/100</span>}{va.warning&&<div className="warn">{va.warning}{va.requested_notes?.length?` (${va.requested_notes.join("; ")})`:""}</div>}{!va.requested&&<span>Best fit <strong>{va.recommended}</strong> at {va.recommended_suitability}/100 across {va.options.length} vehicle profiles</span>}</div>}
      <div className="riskBox"><div><span className={`risk ${selected.risk.level}`}>{selected.risk.level} risk</span><b>{selected.risk.score}/100</b></div><ul>{selected.risk.main_risks.map((risk,i)=><li key={risk}>{i===0?<AlertTriangle size={15}/>:<Info size={15}/>}<span>{risk}</span></li>)}</ul></div>
      <div className="conditions"><div><CloudRain/><span><small>WEATHER · {selected.weather.data_status}</small><strong>{selected.weather.condition}</strong><em>{selected.weather.rainfall_mm} mm rainfall</em></span></div><div><Workflow/><span><small>TERRAIN · {selected.terrain.data_status}</small><strong>{selected.terrain.classification}</strong><em>{selected.terrain.average_slope}° average slope</em></span></div></div>
      {hazard&&<div className={`hazardBanner ${hazard.status}`} style={{marginTop:12}}><ShieldAlert size={15}/><span><strong>{HAZARD_STATUS_TEXT[hazard.status]||label(hazard.status)}</strong>{hazard.status!=="unavailable"&&<><br/>{hazard.zones_crossed} zone(s) · {hazard.affected_distance_km} km · {hazard.historical_incidents_nearby} incident(s) nearby</>}{hazard.reasons?.[0]&&<><br/>{hazard.reasons[0]}</>}</span></div>}
      {selected.accessibility.explanations&&(selected.accessibility.explanations.negative.length>0||selected.accessibility.explanations.positive.length>0)&&<div className="riskBox" style={{marginTop:12}}><div><span className="eyebrow">ROUTE FACTOR EXPLANATIONS</span></div>{selected.accessibility.explanations.negative.length>0&&<><small style={{fontSize:9,color:"#7d8992"}}>Main negative factors</small><ul className="explainList neg">{selected.accessibility.explanations.negative.map(x=><li key={x}>{x}</li>)}</ul></>}{selected.accessibility.explanations.positive.length>0&&<><small style={{fontSize:9,color:"#7d8992",display:"block",marginTop:6}}>Positive factors</small><ul className="explainList pos">{selected.accessibility.explanations.positive.map(x=><li key={x}>{x}</li>)}</ul></>}</div>}
      <div className="aiInsight"><div><Sparkles size={17}/><strong>AI dispatch insight</strong><span>{gemini==="configured"?"GEMINI LIVE":gemini?"DETERMINISTIC FALLBACK":"CHECKING…"}</span></div><p>{analysis.explanation}</p><button type="button" onClick={()=>setChatOpen(true)}>Ask a follow-up <ArrowRight size={15}/></button></div>
      <div className="confidence"><CheckCircle2 size={16}/><span><strong>Decision confidence: {selected.accessibility.confidence!=null?`${Math.round(selected.accessibility.confidence*100)}%`:"—"}</strong><small>{selected.accessibility.confidence_reasons?.length?selected.accessibility.confidence_reasons[0]:`${factorCount} route factors evaluated`}</small></span></div>
      {analysis.data_sources&&<DataSourcesPanel sources={analysis.data_sources} compact/>}
      {canCreate?<button type="button" className="primaryBtn" style={{width:"100%",justifyContent:"center",marginTop:12}} onClick={()=>setDialog(true)}><PackagePlus size={16}/>Create Delivery</button>:!user&&origin!=="offline-demo"?<p style={{fontSize:10,color:"#7d8992",marginTop:12}}><Link className="tableLink" href="/login">Sign in</Link> to save analyses and turn them into deliveries.</p>:origin==="offline-demo"?<p style={{fontSize:10,color:"#875910",marginTop:12}}>The API is unreachable, so this is the bundled demo; deliveries cannot be created from it.</p>:analysis.persistence_status!=="persisted"?<p style={{fontSize:10,color:"#875910",marginTop:12}}>This analysis was not saved, so a delivery cannot be created from it.</p>:null}
    </aside>
  </div></main>
  {dialog&&recommended&&<CreateDeliveryDialog analysis={analysis} route={recommended} cargoType={cargo} priority={priority} departureTime={departure} onClose={()=>setDialog(false)}/>}
  {chatOpen&&<div className="chatDrawer" role="dialog" aria-label="Route assistant"><div className="chatHead"><div><strong>Route assistant</strong><small>{gemini==="configured"?"Gemini with controlled backend context":"Deterministic fallback · Gemini not configured"} · {selected.name}</small></div><button className="iconBtn" onClick={()=>setChatOpen(false)} aria-label="Close"><X size={16}/></button></div>
    <div className="chatBody">{chat.length===0&&<div className="chatMsg bot">Ask about this analysis: hazards, weather, why a route was recommended, or what data was used. Answers only use the verified backend facts.<span className="src">context: {analysis.routes.length} route(s) · {analysis.data_sources?.length||0} data sources</span></div>}{chat.map((m,i)=><div key={i} className={`chatMsg ${m.role}`}>{m.text}{m.source&&<span className="src">{m.source} · {m.status}</span>}</div>)}{ask.isPending&&<div className="chatMsg bot">Thinking…</div>}{ask.isError&&<div className="chatMsg bot">Assistant unavailable right now.</div>}<div ref={chatEnd}/></div>
    <form className="chatForm" onSubmit={e=>{e.preventDefault();send(question)}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Why is Route B recommended? What hazard data was used?" aria-label="Question"/><button type="submit" disabled={ask.isPending||!question.trim()}><Send size={14}/></button></form></div>}
  </div>;
}
