import uuid
from datetime import datetime
from typing import Any
from app.database.types import spatial
from sqlalchemy import Boolean,DateTime,Float,ForeignKey,Integer,JSON,String,Text
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.database.base import Base,TimestampMixin,UUIDMixin
class User(UUIDMixin,TimestampMixin,Base):
    __tablename__="users";email:Mapped[str]=mapped_column(String(255),unique=True,index=True);password_hash:Mapped[str]=mapped_column(String(255));role:Mapped[str]=mapped_column(String(20),default="operator");is_active:Mapped[bool]=mapped_column(Boolean,default=True)
class Location(UUIDMixin,TimestampMixin,Base):
    __tablename__="locations";name:Mapped[str]=mapped_column(String(255),index=True);display_name:Mapped[str|None]=mapped_column(Text);geometry:Mapped[Any]=mapped_column(spatial("POINT"));bounding_box:Mapped[dict|None]=mapped_column(JSON)
class RouteAnalysis(UUIDMixin,TimestampMixin,Base):
    __tablename__="route_analyses";user_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id"),index=True);source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("locations.id"));destination_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("locations.id"));cargo_type:Mapped[str]=mapped_column(String(40));requested_vehicle:Mapped[str]=mapped_column(String(40));priority:Mapped[str]=mapped_column(String(20));emergency_mode:Mapped[bool]=mapped_column(Boolean,default=False);departure_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));recommended_route_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True);data_quality:Mapped[dict]=mapped_column(JSON);request_parameters:Mapped[dict]=mapped_column(JSON);response_snapshot:Mapped[dict]=mapped_column(JSON);status:Mapped[str]=mapped_column(String(20),default="completed",index=True);routes:Mapped[list["AnalyzedRoute"]]=relationship(back_populates="analysis",cascade="all, delete-orphan")
class AnalyzedRoute(UUIDMixin,TimestampMixin,Base):
    __tablename__="analyzed_routes";analysis_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("route_analyses.id",ondelete="CASCADE"),index=True);provider_route_id:Mapped[str]=mapped_column(String(100));name:Mapped[str]=mapped_column(String(255));geometry:Mapped[Any]=mapped_column(spatial("LINESTRING"));distance_km:Mapped[float]=mapped_column(Float);duration_minutes:Mapped[int]=mapped_column(Integer);eta_minutes:Mapped[int]=mapped_column(Integer);accessibility_score:Mapped[int]=mapped_column(Integer);accessibility_status:Mapped[str]=mapped_column(String(30));risk_score:Mapped[int]=mapped_column(Integer);risk_level:Mapped[str]=mapped_column(String(20),index=True);factors:Mapped[dict]=mapped_column(JSON);warnings:Mapped[list]=mapped_column(JSON);terrain:Mapped[dict]=mapped_column(JSON);recommended_vehicle:Mapped[str]=mapped_column(String(80));is_recommended:Mapped[bool]=mapped_column(Boolean,default=False);analysis:Mapped[RouteAnalysis]=relationship(back_populates="routes")
class RiskZone(UUIDMixin,TimestampMixin,Base):
    __tablename__="risk_zones";dataset_source_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("dataset_sources.id"),index=True);fingerprint:Mapped[str|None]=mapped_column(String(64),unique=True,index=True);category:Mapped[str]=mapped_column(String(30),index=True);severity:Mapped[int]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(20),default="historical");source:Mapped[str]=mapped_column(String(120));geometry:Mapped[Any]=mapped_column(spatial("MULTIPOLYGON"));metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class HistoricalIncident(UUIDMixin,TimestampMixin,Base):
    __tablename__="historical_incidents";dataset_source_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("dataset_sources.id"),index=True);fingerprint:Mapped[str|None]=mapped_column(String(64),unique=True,index=True);category:Mapped[str]=mapped_column(String(40),index=True);severity:Mapped[int]=mapped_column(Integer);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);geometry:Mapped[Any]=mapped_column(spatial("POINT"));source:Mapped[str]=mapped_column(String(120));description:Mapped[str]=mapped_column(Text);metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class WeatherSnapshot(UUIDMixin,TimestampMixin,Base):
    __tablename__="weather_snapshots";analyzed_route_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("analyzed_routes.id",ondelete="CASCADE"),index=True);forecast_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));normalized_data:Mapped[dict]=mapped_column(JSON);provider:Mapped[str]=mapped_column(String(60));status:Mapped[str]=mapped_column(String(20))
class VehicleType(UUIDMixin,TimestampMixin,Base):
    __tablename__="vehicle_types";code:Mapped[str]=mapped_column(String(50),unique=True);name:Mapped[str]=mapped_column(String(100));capabilities:Mapped[dict]=mapped_column(JSON,default=dict);active:Mapped[bool]=mapped_column(Boolean,default=True)
class Delivery(UUIDMixin,TimestampMixin,Base):
    __tablename__="deliveries";identifier:Mapped[str]=mapped_column(String(40),unique=True,index=True);user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id"),index=True);analysis_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("route_analyses.id"));source_location_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("locations.id"));destination_location_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("locations.id"));cargo_type:Mapped[str]=mapped_column(String(40));vehicle:Mapped[str]=mapped_column(String(80));status:Mapped[str]=mapped_column(String(20),index=True);priority:Mapped[str]=mapped_column(String(20));planned_departure:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));eta:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));actual_arrival:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));notes:Mapped[str|None]=mapped_column(Text);status_history:Mapped[list]=mapped_column(JSON,default=list)
class UserReport(UUIDMixin,TimestampMixin,Base):
    __tablename__="user_reports";user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id"),index=True);category:Mapped[str]=mapped_column(String(40));status:Mapped[str]=mapped_column(String(20),index=True);geometry:Mapped[Any]=mapped_column(spatial("POINT"));description:Mapped[str]=mapped_column(Text);metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class DatasetSource(UUIDMixin,TimestampMixin,Base):
    __tablename__="dataset_sources";name:Mapped[str]=mapped_column(String(255));slug:Mapped[str]=mapped_column(String(120),unique=True,index=True);provider:Mapped[str]=mapped_column(String(160));hazard_category:Mapped[str]=mapped_column(String(40));data_type:Mapped[str]=mapped_column(String(40));source_url:Mapped[str|None]=mapped_column(Text);source_organization:Mapped[str]=mapped_column(String(255));dataset_version:Mapped[str]=mapped_column(String(80));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));downloaded_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));ingested_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));record_count:Mapped[int]=mapped_column(Integer,default=0);crs:Mapped[str]=mapped_column(String(30),default="EPSG:4326");coverage_area:Mapped[str|None]=mapped_column(String(255));coverage_bbox:Mapped[list|None]=mapped_column(JSON);status:Mapped[str]=mapped_column(String(20),default="registered",index=True);is_live:Mapped[bool]=mapped_column(Boolean,default=False);provenance_type:Mapped[str]=mapped_column(String(20));license:Mapped[str|None]=mapped_column(String(160));layer_type:Mapped[str]=mapped_column(String(40),default="hazard_zones",index=True);attribution:Mapped[str|None]=mapped_column(Text);period_start:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));period_end:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
