"""initial persistent geospatial schema"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
revision="20260907_0001";down_revision=None;branch_labels=None;depends_on=None
def common():return [sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]
def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table("users",*common(),sa.Column("email",sa.String(255),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False))
    op.create_table("locations",*common(),sa.Column("name",sa.String(255),nullable=False),sa.Column("display_name",sa.Text()),sa.Column("geometry",Geometry("POINT",srid=4326,spatial_index=False),nullable=False),sa.Column("bounding_box",sa.JSON()))
    op.create_table("route_analyses",*common(),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id")),sa.Column("source_id",sa.Uuid(),sa.ForeignKey("locations.id"),nullable=False),sa.Column("destination_id",sa.Uuid(),sa.ForeignKey("locations.id"),nullable=False),sa.Column("cargo_type",sa.String(40),nullable=False),sa.Column("requested_vehicle",sa.String(40),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("emergency_mode",sa.Boolean(),nullable=False),sa.Column("departure_time",sa.DateTime(timezone=True)),sa.Column("recommended_route_id",sa.Uuid()),sa.Column("data_quality",sa.JSON(),nullable=False),sa.Column("request_parameters",sa.JSON(),nullable=False),sa.Column("response_snapshot",sa.JSON(),nullable=False),sa.Column("status",sa.String(20),nullable=False))
    op.create_table("analyzed_routes",*common(),sa.Column("analysis_id",sa.Uuid(),sa.ForeignKey("route_analyses.id",ondelete="CASCADE"),nullable=False),sa.Column("provider_route_id",sa.String(100),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("geometry",Geometry("LINESTRING",srid=4326,spatial_index=False),nullable=False),sa.Column("distance_km",sa.Float(),nullable=False),sa.Column("duration_minutes",sa.Integer(),nullable=False),sa.Column("eta_minutes",sa.Integer(),nullable=False),sa.Column("accessibility_score",sa.Integer(),nullable=False),sa.Column("accessibility_status",sa.String(30),nullable=False),sa.Column("risk_score",sa.Integer(),nullable=False),sa.Column("risk_level",sa.String(20),nullable=False),sa.Column("factors",sa.JSON(),nullable=False),sa.Column("warnings",sa.JSON(),nullable=False),sa.Column("terrain",sa.JSON(),nullable=False),sa.Column("recommended_vehicle",sa.String(80),nullable=False),sa.Column("is_recommended",sa.Boolean(),nullable=False))
    op.create_table("risk_zones",*common(),sa.Column("category",sa.String(30),nullable=False),sa.Column("severity",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("source",sa.String(120),nullable=False),sa.Column("geometry",Geometry("MULTIPOLYGON",srid=4326,spatial_index=False),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False))
    op.create_table("historical_incidents",*common(),sa.Column("category",sa.String(40),nullable=False),sa.Column("severity",sa.Integer(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("geometry",Geometry("POINT",srid=4326,spatial_index=False),nullable=False),sa.Column("source",sa.String(120),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False))
    op.create_table("vehicle_types",*common(),sa.Column("code",sa.String(50),nullable=False,unique=True),sa.Column("name",sa.String(100),nullable=False),sa.Column("capabilities",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False))
    op.create_table("weather_snapshots",*common(),sa.Column("analyzed_route_id",sa.Uuid(),sa.ForeignKey("analyzed_routes.id",ondelete="CASCADE"),nullable=False),sa.Column("forecast_at",sa.DateTime(timezone=True)),sa.Column("normalized_data",sa.JSON(),nullable=False),sa.Column("provider",sa.String(60),nullable=False),sa.Column("status",sa.String(20),nullable=False))
    op.create_table("deliveries",*common(),sa.Column("identifier",sa.String(40),nullable=False,unique=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("analysis_id",sa.Uuid(),sa.ForeignKey("route_analyses.id")),sa.Column("cargo_type",sa.String(40),nullable=False),sa.Column("vehicle",sa.String(80),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("planned_departure",sa.DateTime(timezone=True)),sa.Column("eta",sa.DateTime(timezone=True)))
    op.create_table("user_reports",*common(),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("users.id"),nullable=False),sa.Column("category",sa.String(40),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("geometry",Geometry("POINT",srid=4326,spatial_index=False),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False))
    for table in ["users","locations","route_analyses","analyzed_routes","risk_zones","historical_incidents","weather_snapshots","vehicle_types","deliveries","user_reports"]:op.create_index(f"ix_{table}_created_at",table,["created_at"])
    for table,column in [("locations","geometry"),("analyzed_routes","geometry"),("risk_zones","geometry"),("historical_incidents","geometry"),("user_reports","geometry")]:op.create_index(f"ix_{table}_{column}_gist",table,[column],postgresql_using="gist")
    for table,column in [("route_analyses","user_id"),("route_analyses","status"),("analyzed_routes","analysis_id"),("analyzed_routes","risk_level"),("deliveries","user_id"),("deliveries","status")]:op.create_index(f"ix_{table}_{column}",table,[column])
def downgrade():
    for table in ["user_reports","deliveries","weather_snapshots","vehicle_types","historical_incidents","risk_zones","analyzed_routes","route_analyses","locations","users"]:op.drop_table(table)
