"use client";
import "../platform.css";import "../deliveries/delivery.css";
import {useQuery} from "@tanstack/react-query";
import {PageShell} from "@/components/layout/page-shell";
import {platformApi} from "@/lib/platform-api";
import {PROVENANCE_TEXT,dateOnly,dateTime,label} from "@/lib/format";

const healthTone=(s:string)=>["healthy","online","configured","live"].includes(s)?"live":["not_configured","not_installed","fallback","degraded","disabled"].includes(s)?"estimated":s==="unavailable"?"unavailable":"historical";
const th={textAlign:"left" as const,fontSize:9,color:"#74828d"};
export default function Settings(){
  const health=useQuery({queryKey:["health"],queryFn:platformApi.health,staleTime:30000,retry:0});
  const datasets=useQuery({queryKey:["datasets"],queryFn:platformApi.datasets,staleTime:60000,retry:0});
  const readiness=useQuery({queryKey:["readiness"],queryFn:platformApi.readiness,staleTime:60000,retry:0});
  const layers=useQuery({queryKey:["map-layers"],queryFn:platformApi.mapLayers,staleTime:600000,retry:0});
  const config=useQuery({queryKey:["config"],queryFn:platformApi.config,staleTime:600000,retry:0});
  const weights=Object.fromEntries(Object.entries(config.data?.scoring_weights||{}).map(([k,v])=>[label(k),`${Math.round(v*100)}%`]));
  const r=readiness.data;
  return <PageShell title="Settings" subtitle="Provider health, data readiness, dataset registry and analysis configuration">
    <div className="contentGrid">
      <section className="dataCard"><h2>Provider Status<small>runtime services</small></h2>{health.isLoading?<div className="empty">Checking providers…</div>:health.isError?<div className="empty">Health information unavailable.</div>:<><p style={{fontSize:10,color:"#7d8992",marginTop:0}}>Mode: <strong>{health.data?.mode}</strong> · overall {health.data?.status}</p><table className="provenanceTable"><thead><tr><th style={th}>Service</th><th style={th}>Provider</th><th style={th}>Status</th><th style={th}>Mode</th></tr></thead><tbody>{health.data?.providers.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.provider}</td><td><span className={`badge ${healthTone(p.status)}`}>{label(p.status)}</span></td><td><span className={`badge ${p.mode==="simulated"?"simulated":p.mode==="live"?"live":p.mode==="historical"?"historical":p.mode==="unavailable"?"unavailable":"estimated"}`}>{label(p.mode)}</span></td></tr>)}</tbody></table></>}</section>
      <section className="dataCard"><h2>Data Readiness<small>deployment diagnostics</small></h2>{readiness.isLoading?<div className="empty">Checking readiness…</div>:readiness.isError||!r?<div className="empty">Readiness unavailable.</div>:<><div className="statGrid"><div className="stat"><small>Mode</small><strong>{r.mode==="live"?"LIVE DATA":"DEMO"}</strong><em>database {r.database}</em></div><div className="stat"><small>Hazard intelligence</small><strong>{label(r.hazard_intelligence)}</strong><em>{r.hazard_datasets.length} dataset(s) imported</em></div><div className="stat"><small>Routing / weather</small><strong>{label(r.routing)} / {label(r.weather)}</strong><em>terrain {r.terrain}</em></div><div className="stat"><small>Current feeds</small><strong>Unavailable</strong><em>road closures &amp; live events not connected</em></div></div>{r.missing.length>0&&<ul className="riskList" style={{marginTop:10}}>{r.missing.map(m=><li key={m}><span className="badge unavailable">missing</span><span>{m}</span></li>)}</ul>}<p style={{fontSize:10,color:"#7d8992",marginBottom:0}}>Gemini: {r.gemini}. Scoring weights (from backend): {config.isLoading?"loading…":Object.entries(weights).map(([k,v])=>`${k} ${v}`).join(" · ")||"unavailable"}. Confidence factor weights: {Object.entries(config.data?.confidence_factors||{}).map(([k,v])=>`${label(k)} ${Math.round(v*100)}%`).join(" · ")}. Confidence is computed separately from accessibility and only reflects evidence coverage.</p></>}</section>
    </div>
    <section className="dataCard" style={{marginTop:14}}><h2>Dataset Status<small>hazard evidence registry · read-only, ingested via CLI · dataset age shown from source period, not import time</small></h2>{datasets.isLoading?<div className="empty">Loading dataset registry…</div>:datasets.isError?<div className="empty">Dataset registry unavailable.</div>:!datasets.data?.items.length?<div className="empty"><div><p><strong>No hazard dataset has been imported.</strong></p><p>Route analyses report hazard exposure as <em>unavailable</em> (not zero) until an authoritative dataset is registered with <code>python -m app.ingestion.importer</code>. See docs/authoritative-data.md for GSI / NRSC acquisition steps.</p></div></div>:<div style={{overflowX:"auto"}}><table className="dataTable"><thead><tr><th>Dataset</th><th>Organization</th><th>Layer</th><th>Version</th><th>Dataset period</th><th>Published</th><th>Records</th><th>Last imported</th><th>Provenance</th><th>Coverage</th><th>Status</th></tr></thead><tbody>{datasets.data.items.map(x=><tr key={x.id}><td><strong>{x.name}</strong>{x.attribution&&<div style={{fontSize:9,color:"#7d8992"}}>{x.attribution}</div>}{x.license&&<div style={{fontSize:9,color:"#7d8992"}}>{x.license}</div>}{x.access_method&&<div style={{fontSize:9,color:"#7d8992"}}>Access: {x.access_method}</div>}</td><td>{x.organization}</td><td>{x.layer_label||label(x.layer_type)}<div style={{fontSize:9,color:"#7d8992"}}>{label(x.category)} · {label(x.data_type)}</div></td><td>{x.version}</td><td>{x.dataset_period||"—"}</td><td>{dateOnly(x.published_at)}</td><td>{x.records.toLocaleString()}</td><td>{dateTime(x.last_imported)}</td><td><span className={`badge ${x.provenance}`}>{PROVENANCE_TEXT[x.provenance]||x.provenance}</span>{x.is_live&&<span className="badge live" style={{marginLeft:4}}>Live feed</span>}</td><td>{x.coverage||"—"}{x.coverage_bbox&&<div style={{fontSize:9,color:"#7d8992"}}>bbox {x.coverage_bbox.map(n=>n.toFixed(2)).join(", ")}</div>}</td><td><span className={`badge ${x.status==="imported"?"live":x.status==="failed"?"unavailable":"historical"}`}>{label(x.status)}</span></td></tr>)}</tbody></table></div>}</section>
    <section className="dataCard" style={{marginTop:14}}><h2>Official Remote Layers<small>rendered from official WMS services · not imported into PostGIS</small></h2>{layers.isLoading?<div className="empty">Checking remote layers…</div>:layers.isError||!layers.data?.items.length?<div className="empty">No external map layer configured or reachable.</div>:<table className="provenanceTable"><thead><tr><th style={th}>Layer</th><th style={th}>Organization</th><th style={th}>Provenance</th><th style={th}>Period</th><th style={th}>Attribution</th></tr></thead><tbody>{layers.data.items.map(l=><tr key={l.id}><td>{l.name}<div style={{fontSize:9,color:"#7d8992"}}>{l.note}</div></td><td>{l.organization}</td><td><span className={`badge ${l.provenance}`}>{PROVENANCE_TEXT[l.provenance]||l.provenance}</span></td><td>{l.period||"—"}</td><td style={{fontSize:9}}>{l.attribution}</td></tr>)}</tbody></table>}{health.data?.external_layers?.[0]&&<p style={{fontSize:10,color:"#7d8992",marginBottom:0}}>Service check: {health.data.external_layers[0].status} · {health.data.external_layers[0].layers_available} layer(s) available{health.data.external_layers[0].latency_ms!=null?` · ${health.data.external_layers[0].latency_ms} ms`:""}</p>}</section>
  </PageShell>;
}
